# docker-compose.yml
services:
  backup-manager:
    image: nomad4tech/backup-manager:latest
    container_name: backup-manager
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data       # settings & task config (required)
      - ./backups:/app/backups  # backup files (required)
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped